name: CI

on: 'push'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install

      # Runs a set of commands using the runners shell
      - name: Build with mini-css-extract-plugin 2.4.0
        run: yarn build

      - name: Downgrade to 2.3.0
        run: yarn install -D mini-css-extract-plugin@2.3.0

      - name: Build with mini-css-extract-plugin 2.3.0
        run : yarn build
